# Generated by Django 5.2.14 on 2026-05-24 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodposts', '0002_alter_foodpost_author'),
        ('foodposts', '0003_like'),
    ]

    operations = [
    ]
