# Generated by Django 6.0.5 on 2026-05-27 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodposts', '0008_foodpost_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpost',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
