# Generated by Django 6.0.5 on 2026-05-26 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foodposts', '0005_alter_foodpost_author_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CriticReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taste_rating', models.IntegerField()),
                ('price_rating', models.IntegerField()),
                ('presentation_rating', models.IntegerField()),
                ('service_rating', models.IntegerField()),
                ('atmosphere_rating', models.IntegerField()),
                ('review_text', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('critic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critic_reviews', to='foodposts.foodpost')),
            ],
        ),
    ]
