# Generated by Django 5.2.14 on 2026-05-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_criticreview_atmosphere_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criticreview',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
